[package]
name = "swappy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
bytesize = "1.1.0"
clap = { version = "3.2.8", features = [ "clap_derive" ] }
kstat-rs = "0.2.0"
libc = "0.2.126"
parse_int = "0.6.0"
reedline-repl-rs = "1.0.2"
